# Generated by Django 5.0.3 on 2024-03-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatype', '0005_uploadedcsvfile_inferred_data_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsvfile',
            name='inferred_data_types_readable',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedcsvfile',
            name='original_data_types_readable',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
